### ISSUE TITLE
#hacktoberfest: Create simple header for products in React, based on material ui

### ISSUE THREAD

**Issue by a-tonchev** [a-tonchev/react-boilerplate#14]
For our amazing boilerplate it would be awesome to have such component:

![image](https://user-images.githubusercontent.com/54528540/135729527-f2ffe885-0292-4371-add1-fac925efb16d.png)

which should be also responsive:

![image](https://user-images.githubusercontent.com/54528540/135729573-329bfa9d-d036-447f-954c-bae0ffb93c6b.png)

It should receive main `image url`, `title`, `button link` and `button text`, `4 items as array`, having `price`, `title`, `description`

Instead of CSS you should use the custom `useClasses` component which receives styles as `JSS`, just like here:

https://github.com/a-tonchev/react-boilerplate/blob/master/src/components/dataHandling/CustomCodeBlock.jsx

You may make use of the material ui Grid component to construct the responsive blocks: 

https://mui.com/components/grid/

There is no need imitate exactly the design of the pictures, you can just use the basic material ui design.

More information about how to contribute read under:

https://github.com/a-tonchev/react-boilerplate/blob/master/contributing.md

**Comment by julieg18** [comment]
I'd be happy to work on it! May I be assigned to this issue?

**Comment by a-tonchev** [comment]
@julieg18 Sure ;)

**Comment by a-tonchev** [comment]
@julieg18 very nice done, it looks even better than in the screenshot. :)
