### ISSUE TITLE
#hacktoberfest Create autocomplete filters component based on material ui 

### ISSUE THREAD

**Issue by a-tonchev** [a-tonchev/react-boilerplate#33]
It would be awesome to have nice and responsive autocomplete component:

![image](https://user-images.githubusercontent.com/54528540/194894334-af687836-6e80-4f64-a272-25838a566cfb.png)

Create autocomplete functionality based on material ui and its Autocomplete component.

It should be built based on following data:

```JS
[
  { label: 'Filter name 1', children: [{ label: 'subfilter 1', value: 'subfilter1' }, { label: 'subfilter 2', value: 'subfilter2' }] },
  { label: 'Filter name 2', children: [{ label: 'option 1', value: 'option1' }, { label: 'option 2', value: 'option2' }] }
]
```

On change it will deliver all the selected values. The values are unique, so one array would be enough:

selectedValues === ['option1', 'subfilter2'] ...etc

Instead of CSS you should use the custom useClasses component which receives styles as JSS, just like here:

https://github.com/a-tonchev/react-boilerplate/blob/master/src/components/dataHandling/CustomCodeBlock.jsx

You may make use of the material ui Grid component to construct the responsive blocks:

https://mui.com/components/grid/

There is no need imitate exactly the design of the pictures, you can just use the basic material ui design.

More information about how to contribute read under:

https://github.com/a-tonchev/react-boilerplate/blob/master/contributing.md

**Comment by manojku1803** [comment]
Hey sir, Can you please this assign this issue to me...

**Comment by manojku1803** [comment]
It takes so much time to log in...
What to do then?

**Comment by a-tonchev** [comment]
> It takes so much time to log in... What to do then?

You don't need to login, just use the route /showcase which don't require authentication

**Comment by manojku1803** [comment]
Check the changes

**Comment by a-tonchev** [comment]
@manojku1803 cool, thanks
